name: Deploy to Server with Password

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            wget -O /var/www/html/index.html https://raw.githubusercontent.com/DevStarters-Community/official-website/dev/index.html
